(function () {
const {createState,calculate,processInfo,fmt,eq,sign}=window.Thermo;
const {renderGraph,renderComparison}=window.PVGraph;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let raw=createState(),state=calculate(raw),timer=null;
function particles(){const el=$('#particles');el.innerHTML=Array.from({length:20},(_,i)=>`<i class="particle" style="left:${(i*37)%96}%;top:${(i*61)%92}%;--dx:${(i%2?1:-1)*(8+i%11)}px;--dy:${(i%3-1)*(8+i%8)}px"></i>`).join('')}particles();
function fL(v){return (v*1000).toFixed(2)}
function description(s){const ex=s.direction==='expansion',p=s.process;if(p==='isochoric')return ex?'Heat enters a rigid container; particles speed up, raising pressure.':'Heat leaves the rigid container; particles slow and pressure falls.';if(p==='isothermal')return ex?'The gas expands at constant temperature. Heat enters to replace the energy leaving as work.':'The surroundings compress the gas; matching heat leaves so temperature stays fixed.';if(p==='adiabatic')return ex?'The gas pushes the piston outward with no heat entering. Its internal energy and temperature fall.':'The surroundings push the piston inward with no heat leaving. Internal energy and temperature rise.';return ex?'Heating maintains pressure while gas expands, doing work on the surroundings.':'Cooling maintains pressure while the surroundings compress the gas.'}
function render(){state=calculate(raw);const s=state,info=processInfo[s.process],e=eq(s),ex=s.direction==='expansion';$('#process-kicker').textContent=info.kicker;$('#process-title').textContent=info.title;$('#process-definition').textContent=info.definition;$('#constant-badge').textContent=info.badge;$('#p-value').textContent=(s.P/1000).toFixed(1);$('#v-value').textContent=fL(s.V);$('#t-value').textContent=s.T.toFixed(0);$('#p-change').textContent=`initial: ${(s.Pi/1000).toFixed(1)} kPa`;$('#v-change').textContent=`initial: ${fL(s.Vi)} L`;$('#t-change').textContent=`initial: ${s.Ti.toFixed(0)} K`;$('#progress').value=raw.progress;$('#progress-output').textContent=`${raw.progress}%`;
  const iso=s.process==='isochoric';$('#expand').textContent=iso?'Heating':'Expansion';$('#compress').textContent=iso?'Cooling':'Compression';$('#direction-controls').setAttribute('aria-label',iso?'Thermal direction':'Process direction');$('#progress-label').childNodes[0].nodeValue=iso?'Heating / cooling progress ':'Process progress ';
  $('#q-value').textContent=`${fmt(s.Q)} J`;$('#w-value').textContent=`${fmt(s.W)} J`;$('#u-value').textContent=`${fmt(s.dU)} J`;$('#q-flow').textContent=s.process==='adiabatic'?'Q = 0: insulated':sign(s.Q)==='positive'?'heat enters gas':sign(s.Q)==='negative'?'heat leaves gas':'no heat transfer';$('#w-flow').textContent=sign(s.W)==='positive'?'gas pushes outward':sign(s.W)==='negative'?'surroundings compress':'no piston displacement';$('#u-flow').textContent=sign(s.dU)==='positive'?'T rises; U increases':sign(s.dU)==='negative'?'T falls; U decreases':'temperature fixed';$('#equation').innerHTML=`ΔU = Q − W<br><b>${fmt(s.dU)} J = ${fmt(s.Q)} J − (${fmt(s.W)} J)</b>`;
  const gas=$('#gas'),piston=$('#piston');const h=33+Math.min(75,Math.max(0,(s.V/.0068)*75));gas.style.height=`${h}%`;piston.style.top=`${100-h-9}%`;const heat=Math.max(0,Math.min(1,(s.T-210)/280));gas.style.background=`linear-gradient(180deg,hsl(${214-heat*205} 75% ${69-heat*13}%),hsl(${215-heat*205} 82% ${48-heat*5}%))`;$$('.particle').forEach(x=>x.style.setProperty('--speed',`${Math.max(.18,1.45-s.T/360)}s`));$('#volume-marker').textContent=`${fL(s.V)} L`;$('#motion-label').textContent=raw.progress?(iso?(ex?'heating':'cooling'):(ex?'expanding':'compressing')):'ready';$('#visual-caption').textContent=description(s);$('#heat-arrow').style.opacity=s.process==='adiabatic'||!raw.progress?.2:1;$('#work-arrow').style.opacity=s.process==='isochoric'||!raw.progress?.2:1;
  const heatArrow=$('#heat-arrow'),heatLabel=heatArrow.querySelector('b'),heatOut=sign(s.Q)==='negative';heatLabel.textContent=s.process==='adiabatic'?'Q = 0':heatOut?'−Q':'+Q';heatArrow.classList.toggle('outbound',heatOut);const workArrow=$('#work-arrow'),workLabel=workArrow.querySelector('b'),workIn=sign(s.W)==='negative',workOut=sign(s.W)==='positive';workLabel.textContent=sign(s.W)==='zero'?'W = 0':workIn?'−W':'+W';workArrow.classList.toggle('outbound',workOut);workArrow.classList.toggle('inbound',workIn);
  workArrow.classList.toggle('zero-work',!workIn&&!workOut);workArrow.setAttribute('aria-label',workOut?'Positive work done by the gas':workIn?'Negative work done on the gas':'No work done');
  const heatInactive=s.process==='adiabatic'||!raw.progress;heatLabel.textContent=heatInactive?'Q = 0':heatOut?'−Q':'+Q';heatArrow.classList.toggle('zero-heat',heatInactive);heatArrow.style.opacity=1;
  const idle=!raw.progress;[heatArrow,workArrow].forEach(arrow=>arrow.classList.toggle('is-idle',idle));if(idle){heatArrow.style.opacity=.35;workArrow.style.opacity=.35}
  const arrows={isobaric:[['P','CONSTANT'],['V',ex?'↑ increases':'↓ decreases'],['T',ex?'↑ increases':'↓ decreases']],isochoric:[['P',ex?'↑ increases':'↓ decreases'],['V','CONSTANT'],['T',ex?'↑ increases':'↓ decreases']],isothermal:[['P',ex?'↓ decreases':'↑ increases'],['V',ex?'↑ increases':'↓ decreases'],['T','CONSTANT']],adiabatic:[['P',ex?'↓ decreases':'↑ increases'],['V',ex?'↑ increases':'↓ decreases'],['T',ex?'↓ cools':'↑ warms'],['Q','0 (insulated)']]}[s.process];$('#changes').innerHTML=arrows.map(a=>`<div class="change-line"><b>${a[0]}</b><span>${a[1]}</span></div>`).join('');$('#live-equation').innerHTML=`<b>${e.rule}</b><br>${e.work}`;renderGraph($('#pv-graph'),s);}
const gasLaws={isobaric:{name:"Charles's Law",equation:'V₁ / T₁ = V₂ / T₂',description:'At constant pressure, volume is proportional to absolute temperature.'},isochoric:{name:"Gay-Lussac's Law",equation:'P₁ / T₁ = P₂ / T₂',description:'At constant volume, pressure is proportional to absolute temperature.'},isothermal:{name:"Boyle's Law",equation:'P₁V₁ = P₂V₂',description:'At constant temperature, pressure and volume are inversely proportional.'},adiabatic:{name:'Adiabatic relation',equation:'P₁V₁^γ = P₂V₂^γ',description:'With no heat transfer, pressure and volume follow the adiabatic relation.'}};
function renderLaw(process){const law=gasLaws[process];$('#law-name').textContent=law.name;$('#law-equation').textContent=law.equation;$('#law-description').textContent=law.description;}
function setProcess(p){clearInterval(timer);if(p==='firstlaw'||p==='compare'){$('#simulation').classList.add('hidden');$('#firstlaw').classList.toggle('hidden',p!=='firstlaw');$('#compare').classList.toggle('hidden',p!=='compare');if(p==='compare')renderComparison($('#compare-graph'));}else{$('#simulation').classList.remove('hidden');$('#firstlaw').classList.add('hidden');$('#compare').classList.add('hidden');raw=createState(p,raw.direction,0);render();renderLaw(p)}$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.process===p));}
function resetSimulation(){raw.progress=0;if(timer){clearInterval(timer);timer=null;}$('#play').textContent='▶ Play';}
function setDirection(direction){if(raw.direction!==direction)resetSimulation();raw.direction=direction;$('#expand').classList.toggle('selected',direction==='expansion');$('#compress').classList.toggle('selected',direction==='compression');render();}
$$('.tab').forEach(b=>b.onclick=()=>setProcess(b.dataset.process));$('#progress').oninput=e=>{raw.progress=+e.target.value;render()};$('#expand').onclick=()=>setDirection('expansion');$('#compress').onclick=()=>setDirection('compression');$('#reset').onclick=()=>{resetSimulation();render()};$('#step').onclick=()=>{raw.progress=Math.min(100,raw.progress+10);render()};$('#preset').onclick=()=>{raw.progress=100;render()};$('#play').onclick=()=>{if(timer){clearInterval(timer);timer=null;$('#play').textContent='▶ Play';return}$('#play').textContent='Ⅱ Pause';timer=setInterval(()=>{raw.progress=Math.min(100,raw.progress+1);render();if(raw.progress>=100){clearInterval(timer);timer=null;$('#play').textContent='▶ Play'}},60)};
$('#explain').onclick=()=>{const s=state,ex=s.direction==='expansion';let a= s.process==='adiabatic'?[`Gas ${ex?'expands':'is compressed'}; volume ${ex?'increases':'decreases'}.`,ex?`The gas does work, so W is ${sign(s.W)}.`:`The surroundings do work on the gas, so W is ${sign(s.W)}.`,`No heat crosses the insulated boundary: Q = 0.`,`ΔU = Q − W, so ΔU is ${sign(s.dU)}.`,`Internal energy and temperature ${ex?'decrease; particles slow and blue-shift.':'increase; particles speed and red-shift.'}`]:s.process==='isochoric'?[`The rigid container prevents piston displacement, so V stays constant.`,description(s),`With W = 0, the First Law gives Q = ΔU = ${fmt(s.Q)} J.`,`Temperature and pressure ${ex?'increase':'decrease'} together.`]:[`Volume ${ex?'increases':'decreases'}.`,description(s),`The model calculates ${fmt(s.W)} J of work and ${fmt(s.Q)} J of heat.`,`From ΔU = Q − W, ΔU = ${fmt(s.dU)} J.`,s.process==='isothermal'?'Temperature is constant, so ΔU = 0 and Q = W.':'Pressure is constant; the rectangular P–V area is the work.'];$('#explanation').innerHTML=a.filter(Boolean).map(x=>`<li>${x}</li>`).join('')};
$('#check-signs').onclick=()=>{const actual=[sign(state.Q),sign(state.W),sign(state.dU)],guess=[$('#guess-q').value,$('#guess-w').value,$('#guess-u').value],n=actual.filter((x,i)=>x===guess[i]).length;$('#sign-feedback').textContent=n===3?'Correct — every sign follows ΔU = Q − W.':`${n}/3 correct. Actual: Q ${actual[0]}, W ${actual[1]}, ΔU ${actual[2]}.`};
const cards=Object.entries(processInfo).map(([k,v])=>`<article class="compare-card" data-go="${k}" style="background:${v.color}"><h3>${v.title.replace(' process','')}</h3><p>${v.badge}<br>${k==='isobaric'?'horizontal P–V line':k==='isochoric'?'vertical P–V line':k==='isothermal'?'ΔU = 0 · Q = W':'steeper curve · ΔU = −W'}</p></article>`).join('');$('#comparison-cards').innerHTML=cards;$$('.compare-card').forEach(c=>c.onclick=()=>setProcess(c.dataset.go));render();
const problems=[{text:'An ideal gas does 3700 J of work during an isothermal expansion. How much heat is added, in J?',answer:3700,why:'For an isothermal ideal gas, delta U = 0. Therefore Q = W = +3700 J.'},{text:'100 J of work is done ON a system (so W = -100 J) and its internal energy increases by 260 J. What heat is added, in J?',answer:160,why:'Delta U = Q - W. So 260 = Q - (-100), giving Q = +160 J.'},{text:'An isochoric gas gains 480 J of internal energy. What heat is added, in J?',answer:480,why:'A rigid, isochoric container has W = 0. Thus delta U = Q = +480 J.'}];let problemIndex=0;function loadProblem(){const p=problems[problemIndex];$('#problem-text').textContent=p.text;$('#problem-answer').value='';$('#problem-feedback').textContent='';$('#problem-solution').classList.add('hidden')}$('#new-problem').onclick=()=>{problemIndex=(problemIndex+1)%problems.length;loadProblem()};$('#check-problem').onclick=()=>{const p=problems[problemIndex],ok=Math.abs(Number($('#problem-answer').value)-p.answer)<.01;$('#problem-feedback').textContent=ok?'Correct.':'Check the sign convention.';$('#problem-solution').textContent=p.why;$('#problem-solution').classList.remove('hidden')};
const quiz=[{clue:'A P-V path is a horizontal line. Pressure stays constant while the piston moves.',answer:'Isobaric'},{clue:'The piston is locked. The P-V path is vertical and W = 0.',answer:'Isochoric'},{clue:'The P-V path is curved, temperature is constant, and Q = W.',answer:'Isothermal'},{clue:'The curved P-V path is steeper than an isotherm. No heat crosses the boundary.',answer:'Adiabatic'}];let quizIndex=0;function loadQuiz(){const q=quiz[quizIndex];$('#quiz-clue').textContent=q.clue;$('#quiz-answer').value='Isobaric';$('#quiz-feedback').textContent=''}$('#new-quiz').onclick=()=>{quizIndex=(quizIndex+1)%quiz.length;loadQuiz()};$('#check-quiz').onclick=()=>{$('#quiz-feedback').textContent=$('#quiz-answer').value===quiz[quizIndex].answer?'Correct.':'Not yet - use the constraint clue.'};
})();
