(function () {
const {pathPoints,n,R,gamma}=window.Thermo;
const dims={w:520,h:340,l:58,r:18,t:18,b:44};
function map(svg,maxV,maxP){const {w,h,l,r,t,b}=dims;return {x:v=>l+(v/maxV)*(w-l-r),y:p=>h-b-(p/maxP)*(h-t-b),base:h-b};}
function path(points,m){return points.map((p,i)=>`${i?'L':'M'}${m.x(p.V)} ${m.y(p.P)}`).join(' ')}
function axes(maxV,maxP,m){let g='';for(let i=0;i<5;i++){const x=m.x(maxV*i/4),y=m.y(maxP*i/4);g+=`<line class="gridline" x1="${x}" y1="${m.y(0)}" x2="${x}" y2="${m.y(maxP)}"/><text class="tick" x="${x-8}" y="${m.base+16}">${(maxV*i/4*1000).toFixed(1)}</text><line class="gridline" x1="${m.x(0)}" y1="${y}" x2="${m.x(maxV)}" y2="${y}"/><text class="tick" x="${m.x(0)-38}" y="${y+3}">${(maxP*i/4/1000).toFixed(0)}</text>`}return `${g}<line class="axis" x1="${m.x(0)}" y1="${m.base}" x2="${m.x(maxV)}" y2="${m.base}"/><line class="axis" x1="${m.x(0)}" y1="${m.base}" x2="${m.x(0)}" y2="${m.y(maxP)}"/><text class="axis-label" x="${m.x(maxV)-42}" y="${m.base+34}">V (L)</text><text class="axis-label" transform="translate(16 ${m.y(maxP/2)}) rotate(-90)">P (kPa)</text>`}
function isotherms(m,maxV,maxP){let o='';[220,300,380,460].forEach((T,i)=>{let d='';for(let j=0;j<=50;j++){const V=.0012+j*(maxV-.0012)/50,P=n*R*T/V;if(P<=maxP)d+=`${d?'L':'M'}${m.x(V)} ${m.y(P)}`;}o+=`<path class="isotherm" d="${d}"/><text class="tick" x="${m.x(maxV*.86)}" y="${m.y(n*R*T/(maxV*.86))-3}">T${i+1}</text>`});return o}
function renderGraph(svg,s){const pts=pathPoints(s), maxV=Math.max(.0065,s.V, s.Vi)*1.18,maxP=Math.max(180000,s.P,s.Pi)*1.18,m=map(svg,maxV,maxP),d=path(pts,m),first=pts[0],last=pts[pts.length-1];svg.innerHTML=`<defs><marker id="arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7Z" fill="#2870de"/></marker></defs>${axes(maxV,maxP,m)}${isotherms(m,maxV,maxP)}<path class="area" d="${d} L${m.x(last.V)} ${m.base} L${m.x(first.V)} ${m.base}Z"/><path class="path" d="${d}"/><line class="direction-line" x1="${m.x(pts[Math.max(0,pts.length-5)].V)}" y1="${m.y(pts[Math.max(0,pts.length-5)].P)}" x2="${m.x(last.V)}" y2="${m.y(last.P)}"/><circle class="state-initial" cx="${m.x(first.V)}" cy="${m.y(first.P)}" r="5"/><circle class="state-current" cx="${m.x(last.V)}" cy="${m.y(last.P)}" r="6"/><text class="tick" x="${m.x(first.V)+8}" y="${m.y(first.P)-9}">initial</text><text class="tick" x="${m.x(last.V)+8}" y="${m.y(last.P)-9}">current</text>`; svg.dataset.maxV=maxV;svg.dataset.maxP=maxP;}
function renderComparison(svg){const maxV=.007,maxP=220000,m=map(svg,maxV,maxP);const iso=Array.from({length:61},(_,i)=>({V:.002+i*.00007,P:101325*.004/(.002+i*.00007)}));const ad=Array.from({length:61},(_,i)=>({V:.002+i*.00007,P:101325*Math.pow(.004/(.002+i*.00007),gamma)}));svg.innerHTML=`${axes(maxV,maxP,m)}${isotherms(m,maxV,maxP)}<path class="comparison-path" stroke="#ee7758" d="${path(iso,m)}"/><path class="comparison-path" stroke="#7b5fc8" d="${path(ad,m)}"/><path class="comparison-path" stroke="#2870de" d="M${m.x(.002)} ${m.y(101325)} L${m.x(.006)} ${m.y(101325)}"/><path class="comparison-path" stroke="#2eaa88" d="M${m.x(.004)} ${m.y(50000)} L${m.x(.004)} ${m.y(180000)}"/><text class="axis-label" x="${m.x(.0059)}" y="${m.y(78000)}">isothermal</text><text class="axis-label" x="${m.x(.0056)}" y="${m.y(45000)}">adiabatic</text>`}
window.PVGraph={renderGraph,renderComparison};
})();
